### ISSUE TITLE
ドッグランの情報まとめる

### ISSUE THREAD

**Issue by Shota-Yukawa** [wanrun-develop/wanrun#36]
やっぱり、まず消費者ユーザーを増やさないと話にならない。
まず、運営側が介入しなくてもドッグラン情報のプラットフォームとしての価値を生む必要がある。

その土台となる、ドッグランの情報をいかに網羅的か、かつ正確さが必要。

情報の宝箱であるgoogle様のAPIを使用し、データを取得
表示だけなら、フロントがしてもいいが、今後ドッグラン運営側からの情報更新もあると考えると、wanrun側でのデータ管理も必要。。

だが、googleのデータをずっと保持していても情報が古くなったり、規約に違反する。
どう管理するか、また、どう運営側の更新と保つか、考える。

**Comment by kkkkkkkkazuya** [comment]
定期的にバッチとかで取得し続けるような仕組みが必要だな〜

**Comment by Shota-Yukawa** [comment]
googleが持ってるデータを私たちがDBに入れるメリットはほぼない
・規約問題
・情報の陳腐化

つまり。
・googleが持ってる情報のみの場合は、google apiでの整形等のみを行い、フロントに返す。
・その際に、運営側からの情報提供があれば、そっちを優先する。（運営側がついたら）

ま、当たり前ですね。

なので、ユーザーが何かドッグランを探すフロー
・ユーザーがwanrunに来る
・位置情報があれば、一旦それを元に周囲のドッグラン情報を取得
・ユーザーが検索条件をつける
→都道府県/市町村や、目印の場所（駅など）
・それをフロントがバックに届ける
・バックで、google apiを使って、条件内でのドッグランを検索
・palce idで、運営側の情報提供があればそっち優先
・データを整形して、返す

**Comment by Shota-Yukawa** [comment]
ドッグラン検索時と一つのドッグラン詳細を表示する時で、データ量を変える必要があるな

・検索時
できるだけ、ドッグランの数を表示させたいので、最低限の情報
ユーザーが、取捨選択できる情報のみ

・詳細
言わずもがな、全情報

**Comment by Shota-Yukawa** [comment]
### 決めること
- フロントがすることと、バックがすることの線引き
  - 正直、google place apiはちょいと扱いづらいので、バックでできるだけ取得/整形したい
  - ただ、googleの画像とかはフロントにとってきてもらったり、マップとして、表示してもらう必要もある。
  - フロントの方が効率的なのがあれば、フロントで
- 必要なplace情報のフィールドの精査
  - 検索時と詳細画面で
  - 画面との相談
  - ま、いうて、頭でっかちになってもあれなので、今後修正は絶対入るから一旦作る

**Comment by Shota-Yukawa** [comment]
> 定期的にバッチとかで取得し続けるような仕組みが必要だな〜

あ

**Comment by Shota-Yukawa** [comment]
google palce docs

- 金額別フィールド
https://developers.google.com/maps/documentation/places/web-service/usage-and-billing?hl=ja#preferred-placedetails

- フィールド一覧
https://developers.google.com/maps/documentation/places/web-service/data-fields?hl=ja

- レスポンスの型
https://developers.google.com/maps/documentation/places/web-service/reference/rest/v1/places?hl=ja#methods

**Comment by Shota-Yukawa** [comment]
placeIdを元に、google情報とDB情報を選別して返すように作った

placeIdで下記を返す。
ChIJa8cyXFKJGGAR7L7y1nym8E0
``` :json
{
    "dogrun_id": 1,
    "dogrun_manager_id": 0,
    "place_id": "ChIJa8cyXFKJGGAR7L7y1nym8E0",
    "name": "辰巳の森ドッグラン",
    "address": {
        "postcode": "124-0011",
        "address": "江東区辰巳２丁目７"
    },
    "location": {
        "latitude": 35.6483692,
        "longitude": 139.8169404
    },
    "business_status": "OPERATIONAL",
    "now_open": false,
    "business_day": 3,
    "holiday": 1,
    "open_time": "08:00:00",
    "close_time": "21:00:00",
    "description": "テストドッグラン1",
    "google_rating": 0,
    "user_rating_count": 0,
    "dogrun_tags": [
        {
            "dogrun_tag_id": 1,
            "tag_id": 1,
            "tag_idag_name": "屋外",
            "description": "屋外のドッグランがあります。"
        },
        {
            "dogrun_tag_id": 1,
            "tag_id": 8,
            "tag_idag_name": "無料駐車場あり",
            "description": "施設に無料駐車場がございます。"
        },
        {
            "dogrun_tag_id": 1,
            "tag_id": 15,
            "tag_idag_name": "海が見える",
            "description": "施設から海が見えます。"
        }
    ],
    "create_at": "0001-01-01T00:00:00Z",
    "update_at": "0001-01-01T00:00:00Z"
}
```
